<?php
namespace app\admin\controller;
use think\Controller;

class Category extends Controller
{
    /**
     * @var 属性,方便所有方法调用
     */
    private $category;

    /**
     * 初始化分类模型,赋值给属性$category
     */
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->category = model("Category");
    }

    /**
     * 分类列表
     * @return mixed返回一级分类列表
     */
    public function index()
    {
        // 获取parentID,默认值0,整型
        $parentID = input('get.parent_id',0,'intval');
        // 根据parentID获取未删除(正常,待审)分类,传递给模板
        $categorys = $this->category->getFirstCategory($parentID);
        return $this->fetch('',[
            'categorys'=>$categorys,
        ]);
    }

    /**
     * 分类添加模板
     * @return mixed
     */
    public function add()
    {
        // 模型获取正常一级分类,传给模板
        $categorys = $this->category->getNormalFirstCategory();
        return $this->fetch('',[
            'categorys' => $categorys,
        ]);
    }

    /**
     * 获取分类数据,验证(场景)分类数据,保存到数据库
     */
    public function save()
    {
        $data = input('post.');
//        3. 场景设置 中的add--指定字段数据会被验证,忽略其他数据
        $validate = validate('Category');
        if(!$validate->scene('add')->check($data))
        {
            $this->error($validate->getError());
        }
//      4. 提交$data到model层,添加分类
        $res = $this->category->add($data);
        if($res)
        {
            $this->success('新增分类成功');
        }
        else
        {
            $this->error('新增分类失败');
        }



    }
}
