<?php
namespace app\api\controller;
use think\Controller;

class Category extends Controller
{
    /**
     * @var 属性,方便所有方法调用
     */
    private $modle;

    /**
     * 初始化分类模型,赋值给属性model
     */
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->modle = model("Category"); // common/model/Category.php
    }

    /**
     * 分类列表
     * @return mixed返回一级分类列表
     */
    public function getCategoryByParentID()
    {
        $id = input('post.id');
        if(empty($id))
        {
            $this->error('ID不合法');
        }

        // 通过ID(parent_id = id)获取二级分类
        $categorys = $this->modle->getNormalCategorysByParentID($id);
//        dump($citys);exit;
//        return $citys;
        // 返回数据给客户端
        if(empty($categorys))
        {
            return show('0', '所属子类不存在');
        }
        return show('1', 'success', $categorys);

    }


}

