<?php
namespace app\api\controller;
use think\Controller;

class City extends Controller
{
    /**
     * @var 属性,方便所有方法调用
     */
    private $modle;

    /**
     * 初始化城市模型,赋值给属性model
     */
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->modle = model("City");
    }

    /**
     * citys列表
     * @return mixed返回一级city列表
     */
    public function getCitysByParentID()
    {
        $id = input('post.id');
        if(empty($id))
        {
            $this->error('ID不合法');
        }

        // 通过ID获取二级城市
        $citys = $this->modle->getNormalCitysByParentID($id);
//        dump($citys);exit;
//        return $citys;
        // 返回数据给客户端
        if(empty($citys))
        {
            return show('0', '二级城市不存在');
        }
        return show('1', 'success', $citys);

    }


}

